spring:
  datasource:
    # Port, database name, and credentials match docker container setup
    url: "jdbc:postgresql://localhost:5432/clinic_directory"
    username: clinic_admin
    password: Delta66680003*
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true