spring:
  datasource:
    # Port, database name, and credentials match docker container setup
    url: jdbc:sqlserver://localhost:1434;databaseName=master;encrypt=true;trustServerCertificate=true;
    username: sa
    password: ${DB_PASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true